---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-elasticweb-wu123-com-v1-elasticweb
  failurePolicy: Fail
  name: melasticweb.kb.io
  rules:
  - apiGroups:
    - elasticweb.wu123.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - elasticwebs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-elasticweb-wu123-com-v1-elasticweb
  failurePolicy: Fail
  name: velasticweb.kb.io
  rules:
  - apiGroups:
    - elasticweb.wu123.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - elasticwebs
  sideEffects: None
