apiVersion: elasticweb.wu123.com/v1
kind: ElasticWeb
metadata:
  name: elasticweb-sample
spec:
  # TODO(user): Add fields here
  image: tomcat:8.0.18-jre8
  port: 30003
  singlePodQPS: 500
  totalQPS: 600
